In [3]:
import pandas as pd
import numpy as np

In [4]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'Missing'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [24]:
df = pd.DataFrame(people)


df.replace("NA", np.nan, inplace=True)
df.replace("Missing", np.nan, inplace=True)
df.replace("NaN", np.nan, inplace=True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [25]:
df

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [28]:
df.dropna(axis="index", how="all", subset=["last", "email"])

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
5    NaN      NaN      Anonymous@email.com  NaN

In [27]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [33]:
df.fillna(0)

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@email.com   0
6      0        0                        0   0

In [32]:
df.dtypes

first    str
last     str
email    str
age      str
dtype: object

In [35]:
df["age"].mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [40]:
df["age"] = df["age"].astype(float)

In [41]:
df.dtypes

first        str
last         str
email        str
age      float64
dtype: object

In [42]:
df["age"].mean()

np.float64(46.75)