In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv", low_memory=False, index_col="ResponseId")

In [3]:
#Got a DtypeWarning because some columns have mixed data types. Fixed by passing low_memory=False to read_csv, which reads the entire file at once before inferring column types.

In [54]:
#you can specify how many
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [5]:
df.tail(10)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
49181,49182,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49182,49183,I am a developer by profession,35-44 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49183,49184,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,2.0,"Yes, I am new to coding or currently a student",Books / Physical media;Videos (not associated ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49184,49185,"I am not primarily a developer, but I write co...",45-54 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,"Caring for dependents (children, elderly, etc....",30.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49185,49186,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Number of rows and columns 
df.shape

(49191, 172)

In [7]:
#Number of rows and columns and all of the data type
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

In [8]:
df.dtypes

ResponseId               int64
MainBranch                 str
Age                        str
EdLevel                    str
Employment                 str
                        ...
AIAgentExtWrite            str
AIHuman                    str
AIOpen                     str
ConvertedCompYearly    float64
JobSat                 float64
Length: 172, dtype: object

In [9]:
pd.set_option('display.max_columns', 172)

In [58]:
schema_df= pd.read_csv('schema.csv', index_col="qname")

In [11]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [7]:
people = {
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Doe"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@email.com", "JohnDoe@email.com"]
}

In [8]:
#Create a dataframe with the information above

In [9]:
df = pd.DataFrame(people)

In [10]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [16]:
df["email"]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [17]:
df.email

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [18]:
df[["last", "email"]]

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com

In [19]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [20]:
#iloc = access rows and columns by integer location
df.iloc[[0,1], 2]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: str

In [21]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [22]:
#loc = access rows and columns by label
df.loc[[0,1], ["first", "last"]]

   first     last
0  Corey  Schafer
1   Jane      Doe

In [23]:
df.shape

(3, 3)

In [25]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [26]:
list(df.columns)

['first', 'last', 'email']

In [33]:
#value_counts() returns the number of occurrences of each unique value in a column, sorted from most to least frequent.
df["Country"].value_counts()

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
                                                        ...
San Marino                                                 1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, Length: 177, dtype: int64

In [34]:
#df.loc[row_label, column_label] - first argument is the row label, second is the column label.
df.loc[0:2, "Country":"LanguageChoice"]

       Country               Currency  CompTotal LanguageChoice
0      Ukraine      EUR European Euro    52800.0            Yes
1  Netherlands      EUR European Euro    90000.0            Yes
2      Ukraine  UAH Ukrainian hryvnia  2214000.0            Yes

In [38]:
df["email"]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [42]:
df.set_index("email", inplace=True)

In [43]:
df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [44]:
df.index

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com'], dtype='str', name='email')

In [47]:
df.loc["JohnDoe@email.com", "last"]

'Doe'

In [49]:
df.iloc[0]

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: str

In [50]:
df.reset_index(inplace=True)

In [51]:
df

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe

In [68]:
list(df.columns)

['MainBranch',
 'Age',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'WorkExp',
 'LearnCodeChoose',
 'LearnCode',
 'LearnCodeAI',
 'AILearnHow',
 'YearsCode',
 'DevType',
 'OrgSize',
 'ICorPM',
 'RemoteWork',
 'PurchaseInfluence',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechOppose_1',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_16',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'Industry',
 'JobSatPoints_1',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_16',
 'JobSatPoints_15_TEXT',
 'AIThreat',
 'NewRole',
 'ToolCountWork',
 'ToolCountPersonal',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseChoice',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DatabaseAdmired',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'PlatformChoice',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PlatformAdmired',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeChoice',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WebframeAdmired',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvsChoice',
 'DevEnvsHaveWorkedWith',
 'DevEnvsWantToWorkWith',
 'DevEnvsAdmired',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveWorkedWith',
 'SOTagsWantToWorkWith',
 'SOTagsAdmired',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OfficeStackAsyncAdmired',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveWorkedWith',
 'CommPlatformWantToWorkWith',
 'CommPlatformAdmired',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIModelsChoice',
 'AIModelsHaveWorkedWith',
 'AIModelsWantToWorkWith',
 'AIModelsAdmired',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'SOAccount',
 'SOVisitFreq',
 'SODuration',
 'SOPartFreq',
 'SO_Dev_Content',
 'SO_Actions_1',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_9',
 'SO_Actions_7',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SOComm',
 'SOFriction',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently partially AI',
 "AIToolDon't plan to use AI for this task",
 'AIToolPlan to partially use AI',
 'AIToolPlan to mostly use AI',
 'AIToolCurrently mostly AI',
 'AIFrustration',
 'AIExplain',
 'AIAgents',
 'AIAgentChange',
 'AIAgent_Uses',
 'AgentUsesGeneral',
 'AIAgentImpactSomewhat agree',
 'AIAgentImpactNeutral',
 'AIAgentImpactSomewhat disagree',
 'AIAgentImpactStrongly agree',
 'AIAgentImpactStrongly disagree',
 'AIAgentChallengesNeutral',
 'AIAgentChallengesSomewhat disagree',
 'AIAgentChallengesStrongly agree',
 'AIAgentChallengesSomewhat agree',
 'AIAgentChallengesStrongly disagree',
 'AIAgentKnowledge',
 'AIAgentKnowWrite',
 'AIAgentOrchestration',
 'AIAgentOrchWrite',
 'AIAgentObserveSecure',
 'AIAgentObsWrite',
 'AIAgentExternal',
 'AIAgentExtWrite',
 'AIHuman',
 'AIOpen',
 'ConvertedCompYearly',
 'JobSat']

In [72]:
schema_df.loc["YearsCode", "question"]

'Including any education, how many years have you been coding in total?  Please round to the nearest whole number, excluding any decimal points.'

In [71]:
schema_df.sort_index()

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
...,...,...,...,...,...
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [15]:
filt = (df["last"] == "Schafer") | (df["first"] == "John")

In [18]:
df.loc[~filt, "email"]

1    JaneDoe@email.com
Name: email, dtype: str

In [43]:
countries = ["United States", "Brazil", "Ukraine","Canada", "Russia"]
high_salary = (df["ConvertedCompYearly"] > 180000) & (df["Country"].isin(countries)) & (df["LanguageHaveWorkedWith"].str.contains("Python", na=False))

In [44]:
df.loc[high_salary, ["Country", "LanguageHaveWorkedWith", "WorkExp", "ConvertedCompYearly"]]

,Country,LanguageHaveWorkedWith,WorkExp,ConvertedCompYearly
ResponseId,,,,
544,Canada,C;C++;Kotlin;Python,30.0,218875.0
957,Canada,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,25.0,221064.0
1046,Canada,HTML/CSS;JavaScript;Python;Ruby;SQL;TypeScript,16.0,248058.0
1281,Canada,Bash/Shell (all shells);C#;HTML/CSS;JavaScript...,19.0,218875.0
2096,Canada,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...,21.0,200635.0
2145,Canada,Bash/Shell (all shells);Java;Python,19.0,364792.0
2310,Canada,HTML/CSS;Java;JavaScript;Python;Ruby;SQL,16.0,198447.0
2536,Canada,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,10.0,196988.0
2962,Canada,Bash/Shell (all shells);Dart;HTML/CSS;JavaScri...,4.0,210000.0
3082,Canada,Delphi;Python;SQL,35.0,182396.0
3415,Canada,Bash/Shell (all shells);C#;C++;Groovy;Lua;Powe...,23.0,350200.0
4871,Canada,Bash/Shell (all shells);Python;Swift,8.0,218875.0
4906,Canada,C;C++;Go;Groovy;HTML/CSS;Java;Python;Rust;SQL,30.0,284538.0
5415,Canada,Bash/Shell (all shells);PHP;Python;Ruby;Rust,10.0,204283.0
5770,Canada,Bash/Shell (all shells);C++;Python;Rust,45.0,185000.0
5846,Canada,Assembly;C;C#;GDScript;Go;HTML/CSS;JavaScript;...,20.0,182396.0
5953,Canada,HTML/CSS;JavaScript;Python;SQL,4.0,729584.0
8604,Canada,Python;SQL,10.0,200635.0
8632,Canada,Java;JavaScript;Python;Scala;SQL,10.0,277242.0
11118,Canada,Bash/Shell (all shells);HTML/CSS;Python;Scala;...,20.0,218875.0
11275,Brazil,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...,20.0,210252.0
11407,Canada,Bash/Shell (all shells);C;Java;JavaScript;Pyth...,23.0,182396.0
11825,Canada,C++;Python;Rust;TypeScript,10.0,510708.0
12078,Canada,Bash/Shell (all shells);C#;Java;JavaScript;Pyt...,18.0,183456.0
14243,Canada,Bash/Shell (all shells);Go;JavaScript;Python;T...,25.0,189692.0
16954,Canada,Bash/Shell (all shells);C#;HTML/CSS;JavaScript...,12.0,182396.0
18194,Canada,HTML/CSS;JavaScript;Kotlin;Python;SQL;TypeScript,17.0,182396.0
18825,Canada,Bash/Shell (all shells);C;C++;Go;Java;JavaScri...,7.0,218875.0
19019,Canada,Bash/Shell (all shells);C;C++;HTML/CSS;MATLAB;...,13.0,200635.0
20866,Canada,Assembly;Bash/Shell (all shells);C++;Python;Rust,10.0,364792.0
21017,Canada,Assembly;C#;C++;HTML/CSS;JavaScript;Perl;PHP;P...,30.0,196988.0
23399,Canada,Java;JavaScript;Lua;Perl;Python;TypeScript,18.0,240763.0
24044,Canada,Assembly;Bash/Shell (all shells);C;C#;C++;Go;H...,30.0,452342.0
26501,Canada,Elixir;Go;HTML/CSS;JavaScript;Python;Ruby;Rust...,15.0,199176.0
26599,Canada,Bash/Shell (all shells);Erlang;Go;HTML/CSS;Jav...,30.0,182396.0
27272,Canada,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...,20.0,189692.0
27345,Canada,Bash/Shell (all shells);C;C++;HTML/CSS;JavaScr...,16.0,182396.0
27378,Canada,Go;Python,13.0,237115.0
28225,Canada,Bash/Shell (all shells);GDScript;Go;HTML/CSS;J...,20.0,229819.0
30182,Canada,Bash/Shell (all shells);JavaScript;Lua;PowerSh...,10.0,218875.0
30616,Canada,Assembly;Bash/Shell (all shells);C;HTML/CSS;Ja...,17.0,182396.0
30729,Brazil,Bash/Shell (all shells);Elixir;Go;Kotlin;Python,17.0,6371285.0
31599,Canada,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,2.0,218875.0
31956,Canada,Bash/Shell (all shells);C;C++;Java;JavaScript;...,48.0,542810.0
35675,Brazil,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,1.0,182037.0
35687,Canada,C;C++;HTML/CSS;JavaScript;Python;Ruby;Rust;Swift,8.0,242951.0
37367,Canada,Java;Kotlin;Python;SQL,5.0,583667.0
38571,Canada,Bash/Shell (all shells);Go;Python,16.0,215227.0
40342,Canada,Bash/Shell (all shells);C;C++;Java;JavaScript;...,15.0,182396.0
40576,Canada,Assembly;Bash/Shell (all shells);C;C++;Go;Lua;...,21.0,218875.0
40783,Canada,C;Go;Python,9.0,182396.0
44880,Canada,Go;Python,15.0,200635.0
44958,Canada,Bash/Shell (all shells);C#;GDScript;Go;JavaScr...,15.0,218875.0
45580,Canada,HTML/CSS;JavaScript;Python;SQL;TypeScript,15.0,189692.0
45837,Canada,Bash/Shell (all shells);JavaScript;Perl;Python...,30.0,182396.0
48429,Ukraine,Assembly;C#;GDScript;HTML/CSS;JavaScript;Micro...,NaN,10000000.0

In [39]:
filt = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

In [41]:
df.loc[filt, "LanguageHaveWorkedWith"]

ResponseId
5        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
8        Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
9                                        Java;Python;Scala
16       Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...
18                          HTML/CSS;JavaScript;Python;SQL
                               ...
49144            HTML/CSS;JavaScript;Python;SQL;TypeScript
49146    Assembly;Bash/Shell (all shells);C;C++;Python;...
49176    Bash/Shell (all shells);C#;C++;GDScript;HTML/C...
49177    Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
49178    Bash/Shell (all shells);HTML/CSS;Lisp;PowerShe...
Name: LanguageHaveWorkedWith, Length: 18466, dtype: str

In [10]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [11]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [ ]:
#Rename all columns name

In [12]:
df.columns = ["first_name", "last_name", "email"]

In [13]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [24]:
#Uppercase all

df.columns= [x.lower() for x in df.columns]
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [25]:
df.columns = df.columns.str.replace(" ", "_")
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [29]:
#Change Some Columns

df.rename(columns={"first_name": "first",
                   "last_name":  "last"}, inplace=True)

df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [36]:
df.loc[2, ["last", "email"]] = ["Smith", "JohnSmith@email.com"]

In [37]:
 df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith      JohnSmith@email.com

In [40]:
df.loc[2, "last"] = "Doe"

In [41]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe      JohnSmith@email.com

In [42]:
df.at[2, "email"] = "JohnDoe@email.com"

In [43]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [54]:
filt = (df["email"] == "JohnDoe@email.com")
df.loc[filt, "last"] = "Smith"

In [55]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith        JohnDoe@email.com

In [59]:
df["email"] = df["email"].str.lower()

In [61]:
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John    Smith        johndoe@email.com

In [ ]:
apply
map
applymap
replace

In [62]:
df["email"].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [66]:
def update_email(email):
    return email.upper()

In [67]:
#apply() takes a function and applies it to every element in a column. Can be used with a named function or a lambda for concise one-liners.

df["email"].apply(update_email)

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@EMAIL.COM
2          JOHNDOE@EMAIL.COM
Name: email, dtype: str

In [7]:
df["email"].apply(lambda x: x.lower())

0    coreymschafer@gmail.com
1          janedoe@email.com
2          johndoe@email.com
Name: email, dtype: str

In [8]:
df["email"].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [9]:
df.apply(pd.Series.min)

first                      Corey
last                         Doe
email    CoreyMSchafer@gmail.com
dtype: str

In [12]:
df.apply(lambda x: x.min())

first                      Corey
last                         Doe
email    CoreyMSchafer@gmail.com
dtype: str

In [14]:
df.map(len)

   first  last  email
0      5     7     23
1      4     3     17
2      4     3     17

In [16]:
df.map(str.lower)

   first     last                    email
0  corey  schafer  coreymschafer@gmail.com
1   jane      doe        janedoe@email.com
2   john      doe        johndoe@email.com

In [26]:
df["first"].map({"Corey": "Caio"})

0    Caio
1     NaN
2     NaN
Name: first, dtype: str

In [28]:
df["first"] = df["first"].replace({"Corey": "Caio"})

In [31]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.rename(columns = {"ConvertedCompYearly": "SalaryUSDYearly"})

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSDYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df["first"] + "  " + df["last"]

0    Corey  Schafer
1         Jane  Doe
2         John  Doe
dtype: str

In [13]:
df["full_name"] = df["first"] + "  " + df["last"]
df

   first     last                    email       full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey  Schafer
1   Jane      Doe        JaneDoe@email.com       Jane  Doe
2   John      Doe        JohnDoe@email.com       John  Doe

In [15]:
df.drop(columns=["first", "last"], inplace=True)

In [16]:
df

                     email       full_name
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe
2        JohnDoe@email.com       John  Doe

In [18]:
df["full_name"].str.split("  ", expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [21]:
df[["first", "last"]] = df["full_name"].str.split("  ", expand=True)

In [22]:
df

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe   Jane      Doe
2        JohnDoe@email.com       John  Doe   John      Doe

In [27]:
pd.concat([df, pd.DataFrame({"first": ["Tony"]})], ignore_index=True)

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe   Jane      Doe
2        JohnDoe@email.com       John  Doe   John      Doe
3                      NaN             NaN   Tony      NaN

In [28]:
people = {
    "first": ["Zé", "Balão"],
    "last": ["Hanna", "Marin"],
    "email": ["darksouls@gmail.com", "soulsdark@email.com"]
}

df2 = pd.DataFrame(people)

In [29]:
df2

   first   last                email
0     Zé  Hanna  darksouls@gmail.com
1  Balão  Marin  soulsdark@email.com

In [34]:
df3 = pd.concat([df, df2], ignore_index=True)

In [35]:
df3

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe   Jane      Doe
2        JohnDoe@email.com       John  Doe   John      Doe
3      darksouls@gmail.com             NaN     Zé    Hanna
4      soulsdark@email.com             NaN  Balão    Marin

In [37]:
df3.drop(index=4)

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane  Doe   Jane      Doe
2        JohnDoe@email.com       John  Doe   John      Doe
3      darksouls@gmail.com             NaN     Zé    Hanna

In [40]:
# 1. df["last"] == "Doe" - creates a boolean mask, True where last name is "Doe"
# 2. df[mask] - filters the DataFrame, returning only the rows where mask is True
# 3. .index - gets the index labels of those filtered rows
# 4. df.drop(index=...) - drops the rows with those index labels from the DataFrame
df.drop(index=df[df["last"] == "Doe"].index)

                     email       full_name  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer  Corey  Schafer